---
apiVersion: v1
kind: Service
metadata:
  name: bdapi-docs
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  bdapi-docs_mapping
      prefix: /docs/
      service: bdapi-docs
spec:
  selector:
    app: bdapi-docs
  ports:
  - port: 80
    name: http-bdapi-docs
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdapi-docs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bdapi-docs
    spec:
      containers:
      - name: bdapi-docs
        image: buildarium/bdapi-docs:latest
        imagePullPolicy: "Always"
        env:
        - name: ENV
          value: "prod"
        ports:
        - name: http-api
          containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
        # resources:
        #   limits:
        #     cpu: "0.1"
        #     memory: 100Mi
